# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code, and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs test

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Change to Backend Directory
      run: cd backend
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json



    - name: Debug system information
      run: |
        echo "System Information:"
        uname -a
        echo "Disk Usage:"
        df -h
        echo "Memory Usage:"
        free -m
        echo "PM2 Version:"
        pm2 -v

    - name: Stop PM2 services
      run: |
          pm2 stop 0 && pm2 stop 1

    - name: Install Dependencies
      run: |
        cd backend
        npm ci --verbose
        
    - name: Build
      run: |
        cd backend
        npm run build --if-present

        
    - name: Restore PM2 Services
      run: |
        pm2 restart 0 && pm2 restart 1

    - name: PM2 Status
      run: pm2 status 
